module.exports = {
  
  age: "zcMz1Wz4N6n5mDmQUcJj",
  city: "maGlVsMrFuhMeb3bWykr",
  piercingDescription: "vKcwjnJ87yO23WMCU5fc",
  medicalConditions: "naT51Itp3ksLHZqZVJqt",
  submergeAgreement: "ga01V2yn4fc9ShDQJ1Um",
  termsAndConditions: "YfG4ApdjZdvxqbpwlbto",
  occupation: "7BpOJtYcYXFpP50dvuZo",
  fearMedical: "IxUS061NCRo2lB1NUQY2",
  foodAllergies: "OWEnMbq4oRVSmNXQP3CD",
  negativeMetal: "XIcGJH4eSyjnd76DD1EN",
  onAntibiotics: "tMGvzAymrtndzCyb91B8",
  accutaneOrHRT: "n045R9C8QpJnqUBEfdWw",
  takingAccutaneOrHRT: "sLxQdLrtqwr0T556jLn6",
  proneToFainting: "yZ0hKo36PfPNHfBVB8TU",
  pronunciation: "HZBJ8UFSF20dpjRfaUV0",
  pronouns: "4UVPRXM0sbHxCcansvPr",
  consent: "jZS5blnDK8hrwXtucqCr",
  address: "gUQL06ya6qrDHEX7pfvP",
  eaten: "gkK5rbLMrryXJZLJECbw",
  decisionImpare: "qwRgqGs50TcwiLCeOlnj",
  postalCode: "Q7CVGxzGX39hgEk0bvYF",
  photo1URL: "C12ono8IEMOpjj41Lmsv",       
  photo2URL: "JLraVMLSj46zT3UsgHlw",       
  signatureURL: "ILFN8OsAZS0BTOsfo2fs", 

};
